/**
 * Countries and nationalities for the registration form. The school's own
 * countries come first; the rest are alphabetical. The parent picks from
 * this list (typing to search), and the saved value is the plain text name,
 * so nothing downstream (exports, letters, Ed-admin) changes shape.
 */

export type Country = { name: string; nationality: string };

/** Shown first: where the school's families come from. */
export const PRIORITY_COUNTRIES = ["Botswana", "South Africa", "Zimbabwe", "Namibia", "Zambia"] as const;

const ALL: Country[] = [
  { name: "Afghanistan", nationality: "Afghan" },
  { name: "Albania", nationality: "Albanian" },
  { name: "Algeria", nationality: "Algerian" },
  { name: "Andorra", nationality: "Andorran" },
  { name: "Angola", nationality: "Angolan" },
  { name: "Antigua and Barbuda", nationality: "Antiguan or Barbudan" },
  { name: "Argentina", nationality: "Argentine" },
  { name: "Armenia", nationality: "Armenian" },
  { name: "Australia", nationality: "Australian" },
  { name: "Austria", nationality: "Austrian" },
  { name: "Azerbaijan", nationality: "Azerbaijani" },
  { name: "Bahamas", nationality: "Bahamian" },
  { name: "Bahrain", nationality: "Bahraini" },
  { name: "Bangladesh", nationality: "Bangladeshi" },
  { name: "Barbados", nationality: "Barbadian" },
  { name: "Belarus", nationality: "Belarusian" },
  { name: "Belgium", nationality: "Belgian" },
  { name: "Belize", nationality: "Belizean" },
  { name: "Benin", nationality: "Beninese" },
  { name: "Bhutan", nationality: "Bhutanese" },
  { name: "Bolivia", nationality: "Bolivian" },
  { name: "Bosnia and Herzegovina", nationality: "Bosnian or Herzegovinian" },
  { name: "Botswana", nationality: "Motswana" },
  { name: "Brazil", nationality: "Brazilian" },
  { name: "Brunei", nationality: "Bruneian" },
  { name: "Bulgaria", nationality: "Bulgarian" },
  { name: "Burkina Faso", nationality: "Burkinabé" },
  { name: "Burundi", nationality: "Burundian" },
  { name: "Cabo Verde", nationality: "Cabo Verdean" },
  { name: "Cambodia", nationality: "Cambodian" },
  { name: "Cameroon", nationality: "Cameroonian" },
  { name: "Canada", nationality: "Canadian" },
  { name: "Central African Republic", nationality: "Central African" },
  { name: "Chad", nationality: "Chadian" },
  { name: "Chile", nationality: "Chilean" },
  { name: "China", nationality: "Chinese" },
  { name: "Colombia", nationality: "Colombian" },
  { name: "Comoros", nationality: "Comoran" },
  { name: "Congo (Brazzaville)", nationality: "Congolese" },
  { name: "Congo (Democratic Republic)", nationality: "Congolese (DRC)" },
  { name: "Costa Rica", nationality: "Costa Rican" },
  { name: "Côte d'Ivoire", nationality: "Ivorian" },
  { name: "Croatia", nationality: "Croatian" },
  { name: "Cuba", nationality: "Cuban" },
  { name: "Cyprus", nationality: "Cypriot" },
  { name: "Czechia", nationality: "Czech" },
  { name: "Denmark", nationality: "Danish" },
  { name: "Djibouti", nationality: "Djiboutian" },
  { name: "Dominica", nationality: "Dominican" },
  { name: "Dominican Republic", nationality: "Dominican (Republic)" },
  { name: "Ecuador", nationality: "Ecuadorian" },
  { name: "Egypt", nationality: "Egyptian" },
  { name: "El Salvador", nationality: "Salvadoran" },
  { name: "Equatorial Guinea", nationality: "Equatorial Guinean" },
  { name: "Eritrea", nationality: "Eritrean" },
  { name: "Estonia", nationality: "Estonian" },
  { name: "Eswatini", nationality: "Swazi" },
  { name: "Ethiopia", nationality: "Ethiopian" },
  { name: "Fiji", nationality: "Fijian" },
  { name: "Finland", nationality: "Finnish" },
  { name: "France", nationality: "French" },
  { name: "Gabon", nationality: "Gabonese" },
  { name: "Gambia", nationality: "Gambian" },
  { name: "Georgia", nationality: "Georgian" },
  { name: "Germany", nationality: "German" },
  { name: "Ghana", nationality: "Ghanaian" },
  { name: "Greece", nationality: "Greek" },
  { name: "Grenada", nationality: "Grenadian" },
  { name: "Guatemala", nationality: "Guatemalan" },
  { name: "Guinea", nationality: "Guinean" },
  { name: "Guinea-Bissau", nationality: "Bissau-Guinean" },
  { name: "Guyana", nationality: "Guyanese" },
  { name: "Haiti", nationality: "Haitian" },
  { name: "Honduras", nationality: "Honduran" },
  { name: "Hungary", nationality: "Hungarian" },
  { name: "Iceland", nationality: "Icelandic" },
  { name: "India", nationality: "Indian" },
  { name: "Indonesia", nationality: "Indonesian" },
  { name: "Iran", nationality: "Iranian" },
  { name: "Iraq", nationality: "Iraqi" },
  { name: "Ireland", nationality: "Irish" },
  { name: "Israel", nationality: "Israeli" },
  { name: "Italy", nationality: "Italian" },
  { name: "Jamaica", nationality: "Jamaican" },
  { name: "Japan", nationality: "Japanese" },
  { name: "Jordan", nationality: "Jordanian" },
  { name: "Kazakhstan", nationality: "Kazakhstani" },
  { name: "Kenya", nationality: "Kenyan" },
  { name: "Kiribati", nationality: "I-Kiribati" },
  { name: "Kosovo", nationality: "Kosovar" },
  { name: "Kuwait", nationality: "Kuwaiti" },
  { name: "Kyrgyzstan", nationality: "Kyrgyz" },
  { name: "Laos", nationality: "Lao" },
  { name: "Latvia", nationality: "Latvian" },
  { name: "Lebanon", nationality: "Lebanese" },
  { name: "Lesotho", nationality: "Mosotho" },
  { name: "Liberia", nationality: "Liberian" },
  { name: "Libya", nationality: "Libyan" },
  { name: "Liechtenstein", nationality: "Liechtensteiner" },
  { name: "Lithuania", nationality: "Lithuanian" },
  { name: "Luxembourg", nationality: "Luxembourgish" },
  { name: "Madagascar", nationality: "Malagasy" },
  { name: "Malawi", nationality: "Malawian" },
  { name: "Malaysia", nationality: "Malaysian" },
  { name: "Maldives", nationality: "Maldivian" },
  { name: "Mali", nationality: "Malian" },
  { name: "Malta", nationality: "Maltese" },
  { name: "Marshall Islands", nationality: "Marshallese" },
  { name: "Mauritania", nationality: "Mauritanian" },
  { name: "Mauritius", nationality: "Mauritian" },
  { name: "Mexico", nationality: "Mexican" },
  { name: "Micronesia", nationality: "Micronesian" },
  { name: "Moldova", nationality: "Moldovan" },
  { name: "Monaco", nationality: "Monégasque" },
  { name: "Mongolia", nationality: "Mongolian" },
  { name: "Montenegro", nationality: "Montenegrin" },
  { name: "Morocco", nationality: "Moroccan" },
  { name: "Mozambique", nationality: "Mozambican" },
  { name: "Myanmar", nationality: "Burmese" },
  { name: "Namibia", nationality: "Namibian" },
  { name: "Nauru", nationality: "Nauruan" },
  { name: "Nepal", nationality: "Nepali" },
  { name: "Netherlands", nationality: "Dutch" },
  { name: "New Zealand", nationality: "New Zealander" },
  { name: "Nicaragua", nationality: "Nicaraguan" },
  { name: "Niger", nationality: "Nigerien" },
  { name: "Nigeria", nationality: "Nigerian" },
  { name: "North Korea", nationality: "North Korean" },
  { name: "North Macedonia", nationality: "Macedonian" },
  { name: "Norway", nationality: "Norwegian" },
  { name: "Oman", nationality: "Omani" },
  { name: "Pakistan", nationality: "Pakistani" },
  { name: "Palau", nationality: "Palauan" },
  { name: "Palestine", nationality: "Palestinian" },
  { name: "Panama", nationality: "Panamanian" },
  { name: "Papua New Guinea", nationality: "Papua New Guinean" },
  { name: "Paraguay", nationality: "Paraguayan" },
  { name: "Peru", nationality: "Peruvian" },
  { name: "Philippines", nationality: "Filipino" },
  { name: "Poland", nationality: "Polish" },
  { name: "Portugal", nationality: "Portuguese" },
  { name: "Qatar", nationality: "Qatari" },
  { name: "Romania", nationality: "Romanian" },
  { name: "Russia", nationality: "Russian" },
  { name: "Rwanda", nationality: "Rwandan" },
  { name: "Saint Kitts and Nevis", nationality: "Kittitian or Nevisian" },
  { name: "Saint Lucia", nationality: "Saint Lucian" },
  { name: "Saint Vincent and the Grenadines", nationality: "Vincentian" },
  { name: "Samoa", nationality: "Samoan" },
  { name: "San Marino", nationality: "Sammarinese" },
  { name: "São Tomé and Príncipe", nationality: "São Toméan" },
  { name: "Saudi Arabia", nationality: "Saudi" },
  { name: "Senegal", nationality: "Senegalese" },
  { name: "Serbia", nationality: "Serbian" },
  { name: "Seychelles", nationality: "Seychellois" },
  { name: "Sierra Leone", nationality: "Sierra Leonean" },
  { name: "Singapore", nationality: "Singaporean" },
  { name: "Slovakia", nationality: "Slovak" },
  { name: "Slovenia", nationality: "Slovenian" },
  { name: "Solomon Islands", nationality: "Solomon Islander" },
  { name: "Somalia", nationality: "Somali" },
  { name: "South Africa", nationality: "South African" },
  { name: "South Korea", nationality: "South Korean" },
  { name: "South Sudan", nationality: "South Sudanese" },
  { name: "Spain", nationality: "Spanish" },
  { name: "Sri Lanka", nationality: "Sri Lankan" },
  { name: "Sudan", nationality: "Sudanese" },
  { name: "Suriname", nationality: "Surinamese" },
  { name: "Sweden", nationality: "Swedish" },
  { name: "Switzerland", nationality: "Swiss" },
  { name: "Syria", nationality: "Syrian" },
  { name: "Taiwan", nationality: "Taiwanese" },
  { name: "Tajikistan", nationality: "Tajik" },
  { name: "Tanzania", nationality: "Tanzanian" },
  { name: "Thailand", nationality: "Thai" },
  { name: "Timor-Leste", nationality: "Timorese" },
  { name: "Togo", nationality: "Togolese" },
  { name: "Tonga", nationality: "Tongan" },
  { name: "Trinidad and Tobago", nationality: "Trinidadian or Tobagonian" },
  { name: "Tunisia", nationality: "Tunisian" },
  { name: "Turkey", nationality: "Turkish" },
  { name: "Turkmenistan", nationality: "Turkmen" },
  { name: "Tuvalu", nationality: "Tuvaluan" },
  { name: "Uganda", nationality: "Ugandan" },
  { name: "Ukraine", nationality: "Ukrainian" },
  { name: "United Arab Emirates", nationality: "Emirati" },
  { name: "United Kingdom", nationality: "British" },
  { name: "United States", nationality: "American" },
  { name: "Uruguay", nationality: "Uruguayan" },
  { name: "Uzbekistan", nationality: "Uzbek" },
  { name: "Vanuatu", nationality: "Ni-Vanuatu" },
  { name: "Vatican City", nationality: "Vatican" },
  { name: "Venezuela", nationality: "Venezuelan" },
  { name: "Vietnam", nationality: "Vietnamese" },
  { name: "Yemen", nationality: "Yemeni" },
  { name: "Zambia", nationality: "Zambian" },
  { name: "Zimbabwe", nationality: "Zimbabwean" },
];

/** Every country, the school's own first, then A to Z. */
export const COUNTRIES: readonly Country[] = [
  ...PRIORITY_COUNTRIES.map((n) => ALL.find((c) => c.name === n)!),
  ...ALL.filter((c) => !(PRIORITY_COUNTRIES as readonly string[]).includes(c.name)),
];

export const COUNTRY_NAMES: readonly string[] = COUNTRIES.map((c) => c.name);
export const NATIONALITIES: readonly string[] = COUNTRIES.map((c) => c.nationality);

const fold = (s: string) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[’']/g, "'").trim().toLowerCase();

/** A few spellings parents actually type, mapped to the list's entry. */
const ALIASES: Record<string, string> = {
  "botswanan": "Motswana",
  "batswana": "Motswana",
  "tswana": "Motswana",
  "rsa": "South Africa",
  "sa": "South Africa",
  "usa": "United States",
  "united states of america": "United States",
  "america": "United States",
  "uk": "United Kingdom",
  "britain": "United Kingdom",
  "great britain": "United Kingdom",
  "england": "United Kingdom",
  "english": "British",
  "drc": "Congo (Democratic Republic)",
  "dr congo": "Congo (Democratic Republic)",
  "congo": "Congo (Brazzaville)",
  "swaziland": "Eswatini",
  "ivory coast": "Côte d'Ivoire",
  "holland": "Netherlands",
  "uae": "United Arab Emirates",
  "czech republic": "Czechia",
  "burma": "Myanmar",
  "cape verde": "Cabo Verde",
  "macedonia": "North Macedonia",
};

/**
 * The list's own spelling for what the parent typed, or null when it is not
 * a country we know. Case and accents do not matter; a handful of common
 * alternatives (RSA, UK, Swaziland) are accepted.
 */
export function canonicalCountry(raw: string | null | undefined): string | null {
  const q = fold(raw ?? "");
  if (!q) return null;
  const alias = ALIASES[q];
  const target = alias && COUNTRY_NAMES.includes(alias) ? alias : null;
  if (target) return target;
  return COUNTRY_NAMES.find((n) => fold(n) === q) ?? null;
}

export function canonicalNationality(raw: string | null | undefined): string | null {
  const q = fold(raw ?? "");
  if (!q) return null;
  const alias = ALIASES[q];
  if (alias && NATIONALITIES.includes(alias)) return alias;
  const direct = NATIONALITIES.find((n) => fold(n) === q);
  if (direct) return direct;
  // A country name typed into the nationality box ("Botswana") is understood.
  const byCountry = canonicalCountry(raw);
  return byCountry ? (COUNTRIES.find((c) => c.name === byCountry)?.nationality ?? null) : null;
}
