#!/usr/bin/env node
// Prints the SQL that seeds the story assessments (Tumi's Journey) from
// web/content/story/*.json. Idempotent: every row's id is derived from its
// code, and every insert is an upsert, so the script can be re-run after a
// chapter is edited without duplicating anything or touching forms that
// were already sat (forms snapshot questions at launch).
//
//   node web/scripts/story-seed.mjs > /tmp/story-seed.sql
//   psql "$DATABASE_URL" -f /tmp/story-seed.sql
//
// Nothing here is a secret and nothing here decides an admission: it is
// content, the same content a staff member could type into the editor.

import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contentDir = join(here, "..", "content", "story");
const chapters = readdirSync(contentDir)
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => JSON.parse(readFileSync(join(contentDir, f), "utf8")))
  .sort((a, b) => a.grade_sort - b.grade_sort);

const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const uuid = (key) => `md5('story:${key.replace(/'/g, "''")}')::uuid`;
const textArray = (items) =>
  items.length ? `array[${items.map(q).join(", ")}]::text[]` : "'{}'::text[]";
const json = (value) => `${q(JSON.stringify(value))}::jsonb`;

const out = [];
const emit = (s) => out.push(s);

emit("-- Generated by web/scripts/story-seed.mjs. Do not edit; edit the JSON and re-run.");
emit("begin;");
emit("");

for (const chapter of chapters) {
  const bankId = uuid(`bank:${chapter.code}`);
  const templateId = uuid(`template:${chapter.code}`);
  const grade = chapter.grade_sort;

  emit(`-- ${chapter.name}`);
  emit(
    `insert into public.question_banks (id, name, description, status) values (${bankId}, ${q(
      chapter.name,
    )}, ${q(
      "Story assessment items. Seeded from web/content/story; edit there and re-run the seed.",
    )}, 'active')
on conflict (id) do update set name = excluded.name, description = excluded.description, status = 'active';`,
  );

  for (const scene of chapter.scenes) {
    for (const item of scene.items) {
      const qid = uuid(`q:${item.code}`);
      const gradeMin = grade;
      const gradeMax = grade;
      emit(
        `insert into public.questions (id, bank_id, competency_id, type, stem, marks, difficulty, grade_sort_min, grade_sort_max, status, external_code, narration, answer_mode, scene_focus, adult_note)
values (${qid}, ${bankId}, (select id from public.competencies where code = ${q(item.competency)}), ${q(
          item.type,
        )}, ${q(item.narration)}, ${item.marks}, ${item.difficulty}, ${gradeMin}, ${gradeMax}, 'active', ${q(
          item.code,
        )}, ${q(item.narration)}, ${q(item.mode)}, ${textArray(item.focus ?? [])}, ${q(item.note ?? null)})
on conflict (id) do update set bank_id = excluded.bank_id, competency_id = excluded.competency_id, type = excluded.type,
  stem = excluded.stem, marks = excluded.marks, difficulty = excluded.difficulty, grade_sort_min = excluded.grade_sort_min,
  grade_sort_max = excluded.grade_sort_max, status = 'active', external_code = excluded.external_code,
  narration = excluded.narration, answer_mode = excluded.answer_mode, scene_focus = excluded.scene_focus, adult_note = excluded.adult_note;`,
      );

      const options = item.options ?? [];
      if (options.length) {
        // Options are replaced wholesale so a renamed option cannot leave a
        // stale sibling behind. Ids stay stable per (question, position).
        emit(`delete from public.question_options where question_id = ${qid} and position > ${options.length};`);
        options.forEach((label, i) => {
          const oid = uuid(`o:${item.code}:${i + 1}`);
          emit(
            `insert into public.question_options (id, question_id, position, label) values (${oid}, ${qid}, ${i + 1}, ${q(
              label,
            )})
on conflict (id) do update set label = excluded.label, position = excluded.position;`,
          );
        });
      } else {
        emit(`delete from public.question_options where question_id = ${qid};`);
      }

      let answer;
      switch (item.type) {
        case "adult_marked":
          answer = { expected: item.key.expected };
          break;
        case "single_choice": {
          const idx = options.indexOf(item.key.correct);
          if (idx < 0) throw new Error(`${item.code}: correct option "${item.key.correct}" is not among its options`);
          // The option id is a uuid computed in SQL, so build the key in SQL too.
          answer = null;
          emit(
            `insert into public.question_answers (question_id, answer) values (${qid}, jsonb_build_object('option_ids', jsonb_build_array(${uuid(
              `o:${item.code}:${idx + 1}`,
            )})))
on conflict (question_id) do update set answer = excluded.answer;`,
          );
          break;
        }
        case "numeric":
          answer = { value: Number(item.key.value), tolerance: Number(item.key.tolerance ?? 0) };
          break;
        case "short_text":
          answer = { accepted: item.key.accepted };
          break;
        case "ordering": {
          // The authored order is the answer; the key lists the ids in order.
          if (options.length < 2) throw new Error(`${item.code}: ordering needs at least two options`);
          answer = null;
          emit(
            `insert into public.question_answers (question_id, answer) values (${qid}, jsonb_build_object('order', jsonb_build_array(${options
              .map((_, i) => uuid(`o:${item.code}:${i + 1}`))
              .join(", ")})))
on conflict (question_id) do update set answer = excluded.answer;`,
          );
          break;
        }
        default:
          throw new Error(`${item.code}: unsupported type ${item.type}`);
      }
      if (answer) {
        emit(
          `insert into public.question_answers (question_id, answer) values (${qid}, ${json(answer)})
on conflict (question_id) do update set answer = excluded.answer;`,
        );
      }
    }
  }

  emit(
    `insert into public.assessment_templates (id, name, description, grade_sort_min, grade_sort_max, time_limit_minutes, status, delivery, story_character)
values (${templateId}, ${q(chapter.name)}, ${q(
      "A read-aloud story assessment. An adult sits with the child and marks alongside.",
    )}, ${grade}, ${grade}, ${chapter.time_limit_minutes}, 'active', 'story', ${q(chapter.character)})
on conflict (id) do update set name = excluded.name, description = excluded.description, grade_sort_min = excluded.grade_sort_min,
  grade_sort_max = excluded.grade_sort_max, time_limit_minutes = excluded.time_limit_minutes, delivery = 'story',
  story_character = excluded.story_character, status = 'active';`,
  );
  emit(`delete from public.template_sections where template_id = ${templateId} and position > ${chapter.scenes.length};`);

  chapter.scenes.forEach((scene, si) => {
    const sectionId = uuid(`section:${chapter.code}:${scene.key}`);
    // Positions are unique per template, so park every section first and
    // then renumber, or a reordered scene would collide with its neighbour.
    emit(
      `insert into public.template_sections (id, template_id, position, title, subject_id, instructions, selection, scene_key, narration, stop_after_misses)
values (${sectionId}, ${templateId}, ${1000 + si + 1}, ${q(scene.title)}, (select id from public.subjects where code = ${q(
        scene.subject,
      )}), ${q(scene.sees)}, 'fixed', ${q(scene.key)}, ${q(scene.narration)}, ${chapter.stop_after_misses})
on conflict (id) do update set template_id = excluded.template_id, position = excluded.position, title = excluded.title,
  subject_id = excluded.subject_id, instructions = excluded.instructions, selection = 'fixed', scene_key = excluded.scene_key,
  narration = excluded.narration, stop_after_misses = excluded.stop_after_misses;`,
    );
  });
  emit(`update public.template_sections set position = position - 1000 where template_id = ${templateId} and position > 1000;`);

  chapter.scenes.forEach((scene) => {
    const sectionId = uuid(`section:${chapter.code}:${scene.key}`);
    emit(`delete from public.template_section_questions where section_id = ${sectionId};`);
    scene.items.forEach((item, qi) => {
      emit(
        `insert into public.template_section_questions (section_id, question_id, position) values (${sectionId}, ${uuid(
          `q:${item.code}`,
        )}, ${qi + 1});`,
      );
    });
  });
  emit("");
}

emit("commit;");
process.stdout.write(out.join("\n") + "\n");
