import {
  ChartColumn, Blocks, BookOpen, Building2, CalendarDays, CalendarOff, SquareCheck, ClipboardCheck, Columns3, CreditCard,
  Download, FilePenLine, FileText, FolderCheck, GraduationCap, Inbox, LayoutDashboard, ListChecks, Mail, MessageCircle,
  PenLine, RefreshCw, Scale, BadgePercent, ScrollText, School, Send, Settings, ShieldCheck, SlidersHorizontal, Target, TrendingUp, Trash, Users, UserCog, type LucideIcon,
} from "lucide-react";
import type { NavIcon } from "@/components/staff/nav-items";

/** The one place a nav icon name becomes a glyph. */
export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  dashboard: LayoutDashboard,
  applicants: Users,
  assessment: ClipboardCheck,
  tasks: SquareCheck,
  decisions: Scale,
  offers: FileText,
  payments: CreditCard,
  registrations: FolderCheck,
  export: Download,
  students: School,
  reenrolment: RefreshCw,
  analytics: ChartColumn,
  forecast: TrendingUp,
  settings: Settings,
  questions: BookOpen,
  templates: Blocks,
  rubrics: PenLine,
  benchmarks: Target,
  competencies: ListChecks,
  rules: ShieldCheck,
  sessions: CalendarDays,
  holidays: CalendarOff,
  email: Mail,
  whatsapp: MessageCircle,
  offerTemplates: ScrollText,
  agreements: FilePenLine,
  documents: FolderCheck,
  fees: CreditCard,
  promotions: BadgePercent,
  campuses: Building2,
  grades: GraduationCap,
  intakes: CalendarDays,
  staff: UserCog,
  workflow: SlidersHorizontal,
  retention: Trash,
  columns: Columns3,
  outbox: Send,
  jobs: Inbox,
};
