-- ===========================================================================
-- Interview question banks: Pre-school, Primary and Secondary teaching.
--
-- Each bank has core questions (every vacancy in the phase starts with them)
-- and a pool the AI may choose from and tailor to a vacancy's subject and
-- grade. A person approves every question a vacancy asks. Each question has
-- a rubric of five bands, 0 to 4, so a written answer is marked against the
-- same description whoever marks it, person or AI.
--
-- Data only, and upserted by code, so this file can be re-run and a later
-- migration can change wording without touching what a published vacancy
-- froze.
-- ===========================================================================

insert into public.hr_question_banks (code, phase, name, description) values
  ('preschool_teaching', 'preschool', 'Pre-school and early childhood teaching',
   'For teachers and practitioners working with children aged 2 to 6.'),
  ('primary_teaching', 'primary', 'Primary teaching',
   'For class and subject teachers from Stage 1 to Stage 7.'),
  ('secondary_teaching', 'secondary', 'Secondary teaching',
   'For subject teachers from Grade 8 to Grade 12.'),
  ('general_staff', 'general', 'Non-teaching staff',
   'For administration, finance, grounds, kitchen and support staff. Questions to follow.')
on conflict (code) do update set name = excluded.name, description = excluded.description, phase = excluded.phase;

-- One row per question: bank, code, kind, competency, prompt, guidance,
-- word limit, then the descriptors for bands 1 to 4. Band 0 is the same for
-- every question and is added below.
with q(bank, code, kind, competency, prompt, guidance, word_limit, b1, b2, b3, b4, sort_order) as (
  values
  -- -------------------------------------------------------------------------
  -- Pre-school
  -- -------------------------------------------------------------------------
  ('preschool_teaching', 'pre_core_routine', 'core', 'early_years_practice',
   'Describe a typical morning in your classroom, from arrival to snack time. How do you plan routines for children of this age?',
   'Look for a clear, realistic routine with reasons: settling, transitions, play, choice and rest.',
   250,
   'A list of activities with no reasons, or a routine that does not suit young children.',
   'A workable routine, with some idea of why routines matter, but little about transitions or individual children.',
   'A clear routine with reasons: predictability, transitions, a balance of play and adult-led time, and some flexibility.',
   'A thoughtful routine that adapts to individual children, uses visual cues and songs for transitions, balances child-led and adult-led play, and explains how it supports wellbeing and learning.',
   10),
  ('preschool_teaching', 'pre_core_separation', 'core', 'early_years_practice',
   'A three-year-old cries and will not let go of their parent at drop-off every day for two weeks. What do you do, and how do you work with the parent?',
   'Look for empathy, a settling plan, partnership with the parent and patience over time.',
   250,
   'Tells the parent to leave quickly, or blames the child or the parent.',
   'Comforts the child and suggests a short goodbye, but no plan and little partnership with the parent.',
   'A settling plan: a key person, a comfort object, a short, consistent goodbye, and regular updates to the parent.',
   'A planned, gradual approach agreed with the parent, a key person, comfort objects or photos, a consistent goodbye routine, honest updates (a photo or message once settled), and a review after a set time.',
   20),
  ('preschool_teaching', 'pre_core_readiness', 'core', 'pedagogy',
   'How do you know when a four-year-old is ready for early reading or counting? Give an example of a play-based activity you have used for one of them.',
   'Look for observation-based judgement and a concrete, playful activity.',
   250,
   'Uses worksheets or age alone, with no observation.',
   'Mentions some signs of readiness, and gives an activity that is only partly play-based.',
   'Observes interest and skills (sounds, rhymes, one-to-one counting), and describes a clear play-based activity.',
   'Explains readiness through observation across several areas, gives a vivid play-based activity with a clear learning goal, and explains how they would extend or simplify it for different children.',
   30),
  ('preschool_teaching', 'pre_core_biting', 'core', 'classroom_management',
   'One child bites another child. Walk us through what you do in the moment and afterwards, including what you tell both families.',
   'Look for first aid and comfort first, calm and age-appropriate guidance, recording, and confidential, factual communication with both families.',
   250,
   'Punishes the child harshly, or names one child to the other family.',
   'Separates the children and tells the parents, but misses first aid, recording, or confidentiality.',
   'Comforts and treats the bitten child, gives calm guidance to the other child, records the incident, and informs both families without naming the other child.',
   'All of band 3, plus looking for a pattern (teething, frustration, language), a plan to prevent it with the family, closer supervision, and follow-up with both families.',
   40),
  ('preschool_teaching', 'pre_core_safeguarding', 'core', 'safeguarding',
   'You notice unexplained bruises on a child, and the child is unusually quiet and withdrawn. What exactly do you do?',
   'Non-negotiable. A strong answer reports to the designated safeguarding lead the same day, records facts, and does not investigate or confront the family.',
   250,
   'Asks the parent about it first, waits to see, or does nothing. (A person should review any answer in this band.)',
   'Tells someone, but vaguely, or plans to question the child in detail or investigate.',
   'Reports the same day to the designated safeguarding lead, records what they saw factually, and does not confront the family.',
   'All of band 3, plus: listens calmly if the child speaks without leading questions, records the child''s own words, dates and times, never promises secrecy, follows the school policy, and knows when to report outside the school if needed.',
   50),
  ('preschool_teaching', 'pre_core_progress', 'core', 'assessment',
   'How do you record a child''s development, and how do you share it with parents?',
   'Look for regular observation, a clear record, and two-way communication with families.',
   250,
   'No real system, or only an end-of-year report.',
   'Some observations and reports, but irregular or one-way.',
   'Regular observations against developmental areas, a portfolio or learning journal, and regular conversations with parents.',
   'A clear, regular system (observations, photos, samples) linked to developmental goals, used to plan next steps, shared through journals and meetings, and inviting parents to add what they see at home.',
   60),
  ('preschool_teaching', 'pre_pool_assistant', 'pool', 'teamwork',
   'How do you work with a classroom assistant so that both of you know what to do every day?',
   null, 200,
   'Sees the assistant as help with tidying only.',
   'Gives the assistant tasks, but with little planning together.',
   'Shares plans, gives clear roles, and talks with the assistant every day.',
   'Plans with the assistant, uses their observations, gives clear roles for each part of the day, and helps them develop their own skills.',
   110),
  ('preschool_teaching', 'pre_pool_delay', 'pool', 'inclusion',
   'You think a child may have a developmental delay. What do you do?',
   null, 200,
   'Tells the parent the child has a condition, or ignores it.',
   'Watches the child and mentions it to someone, without a clear process.',
   'Observes and records over time, talks with the lead or special needs coordinator, then meets the parents with care.',
   'All of band 3, plus adapts activities at once, avoids labels, agrees next steps and any referral with the family, and reviews progress regularly.',
   120),
  ('preschool_teaching', 'pre_pool_intimate_care', 'pool', 'safeguarding',
   'How do you handle toilet training and changing while protecting the child''s dignity and safety?',
   null, 200,
   'No awareness of dignity or safeguarding.',
   'Some care for dignity, but no awareness of policy.',
   'Follows the intimate care policy, protects privacy, talks to the child, and keeps a record.',
   'All of band 3, plus works with parents on a consistent approach, encourages independence, and understands why the policy protects both the child and the adult.',
   130),
  ('preschool_teaching', 'pre_pool_difficult_day', 'pool', 'communication',
   'A child had a very difficult day. How do you tell the parent at home time?',
   null, 200,
   'Blames the child or says nothing.',
   'Tells the parent the facts, but without care or a plan.',
   'Speaks privately, is honest and kind, and shares what helped.',
   'Speaks privately, starts with something positive, describes facts not labels, asks about home, and agrees a shared plan.',
   140),
  ('preschool_teaching', 'pre_pool_language', 'pool', 'inclusion',
   'A child joins your class speaking little English or Setswana. How do you help them settle and learn?',
   null, 200,
   'Expects the child to pick it up alone.',
   'Some support, such as pairing with a friend.',
   'Uses visuals, routines, gestures and a buddy, and values the home language.',
   'All of band 3, plus learns key words in the home language, involves the family, plans language-rich play, and tracks progress.',
   150),

  -- -------------------------------------------------------------------------
  -- Primary
  -- -------------------------------------------------------------------------
  ('primary_teaching', 'pri_core_lesson', 'core', 'pedagogy',
   'Choose a lesson you are proud of. Tell us its objective, the main activities, and how you checked what learners had learnt.',
   'Look for a clear objective, activities that match it, and a real check of learning.',
   300,
   'A list of activities with no objective or check of learning.',
   'An objective and activities, but the check of learning is weak or missing.',
   'A clear objective, activities that build towards it, and a check of learning during and at the end.',
   'A clear objective, well-sequenced activities with modelling and practice, checks during the lesson that changed what the teacher did, and reflection on what they would improve.',
   10),
  ('primary_teaching', 'pri_core_differentiate', 'core', 'inclusion',
   'In one lesson, how do you teach a learner who is two years behind and a learner who is ahead?',
   'Look for practical, specific differentiation without lowering expectations.',
   250,
   'Gives the weaker learner less to do, or the stronger learner more of the same.',
   'Some differentiation, but general or not practical.',
   'Specific support (scaffolds, resources, adult time) and real stretch (depth, reasoning), within the same lesson objective.',
   'All of band 3, plus uses assessment to group flexibly, keeps high expectations for both, plans next steps, and works with parents or learning support.',
   20),
  ('primary_teaching', 'pri_core_behaviour', 'core', 'classroom_management',
   'Describe how you manage your classroom. What do you do when a learner keeps disrupting the class?',
   'Look for clear routines and expectations, calm consistency, and finding the cause.',
   250,
   'Shouting, humiliating, or sending the learner out as the first step.',
   'Some rules and consequences, applied inconsistently or without finding the cause.',
   'Clear routines and expectations, calm and consistent responses, positive reinforcement, and a private conversation with the learner.',
   'All of band 3, plus looks for the reason behind the behaviour, involves parents and colleagues, keeps a record, and has a plan to rebuild the relationship.',
   30),
  ('primary_teaching', 'pri_core_assessment', 'core', 'assessment',
   'How do you use assessment, during lessons and in tests, to change what you teach next?',
   'Look for formative assessment that actually changes teaching.',
   250,
   'Tests only, with marks recorded and not used.',
   'Some checks of learning, but little evidence they change teaching.',
   'Regular formative checks (questions, exit tickets, mini whiteboards) and test analysis that lead to reteaching or regrouping.',
   'A clear cycle: checks during lessons, analysis of errors, reteaching, feedback learners act on, and tracking over time, with an example.',
   40),
  ('primary_teaching', 'pri_core_safeguarding', 'core', 'safeguarding',
   'A learner tells you that something at home is making them feel unsafe. What do you do?',
   'Non-negotiable. A strong answer listens, never promises secrecy, and reports to the designated safeguarding lead the same day.',
   250,
   'Promises to keep it secret, contacts the family, or does nothing. (A person should review any answer in this band.)',
   'Tells someone, but vaguely, or asks many leading questions.',
   'Listens calmly, does not promise secrecy, reports to the designated safeguarding lead the same day, and records what was said.',
   'All of band 3, plus records the learner''s own words, dates and times, reassures the learner they did the right thing, follows the policy, and does not investigate themselves.',
   50),
  ('primary_teaching', 'pri_core_parent', 'core', 'communication',
   'A parent is unhappy about their child''s marks and comes to see you. How do you handle the conversation?',
   'Look for calm listening, evidence, and an agreed plan.',
   250,
   'Gets defensive, or changes marks to please the parent.',
   'Listens and explains, but with no evidence or plan.',
   'Listens, shows the child''s work and the criteria, explains clearly, and agrees next steps.',
   'All of band 3, plus prepares in advance, keeps the conversation about the child''s learning, follows up in writing, and involves a senior colleague if needed.',
   60),
  ('primary_teaching', 'pri_pool_reading', 'pool', 'pedagogy',
   'How do you help a learner in Stage 3 who is struggling to read?',
   null, 200,
   'More reading aloud with no strategy.',
   'Some strategies, but not systematic.',
   'Assesses the gap, uses systematic phonics and decodable books, and gives regular short practice.',
   'All of band 3, plus tracks progress, works with parents on reading at home, builds confidence and love of reading, and asks for specialist help if progress is slow.',
   110),
  ('primary_teaching', 'pri_pool_technology', 'pool', 'pedagogy',
   'Give an example of how you used technology to improve learning, not only to make a lesson look interesting.',
   null, 200,
   'Technology used for its own sake.',
   'A reasonable use, with little evidence of better learning.',
   'A clear example where technology helped learners practise, create or get feedback.',
   'A clear example with evidence of impact, awareness of screen time and online safety, and a plan for when the technology fails.',
   120),
  ('primary_teaching', 'pri_pool_curriculum', 'pool', 'subject_knowledge',
   'Which curriculum have you taught (for example Cambridge, the Botswana curriculum or CAPS), and how do you plan a term from it?',
   null, 200,
   'Little knowledge of any curriculum.',
   'Knows a curriculum, but plans week by week from the textbook.',
   'Plans a term from the curriculum objectives, with assessment points.',
   'Plans backwards from end-of-term goals, sequences knowledge, builds in review and assessment, and adapts for the class.',
   130),
  ('primary_teaching', 'pri_pool_cocurricular', 'pool', 'professionalism',
   'What could you offer outside the classroom: sport, clubs, music, events?',
   null, 150,
   'Nothing offered.',
   'A general willingness to help.',
   'A specific activity they have led before.',
   'A specific activity they have led, with what learners gained from it and how they would start it here.',
   140),
  ('primary_teaching', 'pri_pool_multilingual', 'pool', 'inclusion',
   'Many of our learners speak two or three languages. How do you support learners whose home language is not English?',
   null, 200,
   'Expects learners to manage alone.',
   'Some support, such as simpler words.',
   'Visuals, vocabulary teaching, talk partners, and valuing home languages.',
   'All of band 3, plus plans language goals alongside subject goals, checks understanding carefully, and involves families.',
   150),

  -- -------------------------------------------------------------------------
  -- Secondary
  -- -------------------------------------------------------------------------
  ('secondary_teaching', 'sec_core_relevance', 'core', 'pedagogy',
   'How do you make your subject matter to teenagers who ask "Why do we need this?"',
   'Look for genuine connections to learners'' lives and futures, and enthusiasm for the subject.',
   250,
   'Says the topic is in the exam.',
   'Some real-world examples, used occasionally.',
   'Planned links to learners'' lives, careers and current events, and lessons that build curiosity.',
   'All of band 3, plus shows the value of the subject itself, gives learners choice and real tasks, and gives a concrete example that worked.',
   10),
  ('secondary_teaching', 'sec_core_exams', 'core', 'assessment',
   'How do you prepare a class for external examinations (such as BGCSE, NSC or IGCSE) without only teaching to the test?',
   'Look for deep understanding first, with targeted exam technique.',
   300,
   'Past papers only.',
   'Covers the syllabus and does past papers, with little about understanding.',
   'Builds understanding through the course, then practises exam technique, timing and command words, using results to target gaps.',
   'All of band 3, plus spaced review, analysis of examiner reports, individual targets, and attention to learner wellbeing before exams.',
   20),
  ('secondary_teaching', 'sec_core_authority', 'core', 'classroom_management',
   'Tell us about a time a learner challenged your authority in front of the class. What happened, and what did you do?',
   'Look for a real example, calm de-escalation, and repairing the relationship.',
   250,
   'Escalated the conflict in public, or has no example.',
   'Handled it, but with little reflection.',
   'Stayed calm, avoided a public battle, dealt with it privately later, and applied consequences fairly.',
   'All of band 3, plus understood the cause, repaired the relationship, involved others where needed, and reflected on what they learnt.',
   30),
  ('secondary_teaching', 'sec_core_drop', 'core', 'inclusion',
   'A learner''s marks suddenly drop. How do you support them?',
   'Look for curiosity about the cause, pastoral care, and a plan.',
   250,
   'Gives a warning or extra homework.',
   'Talks to the learner, but with no plan.',
   'Talks privately to understand the cause, checks with colleagues, contacts home, and agrees a plan.',
   'All of band 3, plus considers wellbeing and safeguarding, works with the pastoral team, monitors progress, and follows up.',
   40),
  ('secondary_teaching', 'sec_core_boundaries', 'core', 'safeguarding',
   'A learner sends you a personal message on social media. What do you do?',
   'Non-negotiable. A strong answer does not reply privately, keeps a record, and reports to the designated safeguarding lead.',
   250,
   'Replies privately or befriends the learner. (A person should review any answer in this band.)',
   'Ignores it, without recording or reporting.',
   'Does not reply privately, keeps a record, and reports it to the designated safeguarding lead.',
   'All of band 3, plus knows the school''s online policy, checks whether the message shows a welfare concern, and keeps their own accounts private.',
   50),
  ('secondary_teaching', 'sec_core_results', 'core', 'professionalism',
   'What is the strongest result you have achieved with a class, and how did you measure it?',
   'Look for a specific result with evidence, and an honest account of what the teacher did.',
   250,
   'No example, or a claim with no evidence.',
   'An example with weak evidence.',
   'A specific result with evidence (results, progress data) and what they did to achieve it.',
   'A specific, well-evidenced result, the actions behind it, what they would repeat, and credit to colleagues and learners.',
   60),
  ('secondary_teaching', 'sec_pool_subject', 'pool', 'subject_knowledge',
   'Explain a difficult idea in your subject as you would to a Grade 9 class. Then say what learners usually get wrong about it.',
   'The AI tailors this to the vacancy''s subject.',
   300,
   'Inaccurate, or not suitable for the age group.',
   'Accurate, but not clearly explained.',
   'Accurate and clear, with a good example, and names a common misconception.',
   'Accurate, clear and engaging, with an example and a check of understanding, and explains how to address the common misconception.',
   110),
  ('secondary_teaching', 'sec_pool_pastoral', 'pool', 'professionalism',
   'What do you think a register or form teacher is for, and what would you do in that role?',
   null, 200,
   'Taking the register only.',
   'Some care for learners, in general terms.',
   'Knows each learner, follows up attendance and behaviour, and is a link to home.',
   'All of band 3, plus plans form time, notices changes in learners, works with the pastoral team, and builds a positive group.',
   120),
  ('secondary_teaching', 'sec_pool_integrity', 'pool', 'professionalism',
   'How do you make sure coursework and homework are the learner''s own work, now that AI tools are easy to use?',
   null, 200,
   'No awareness of the issue.',
   'Relies on banning tools.',
   'Designs tasks that show the process, checks drafts, and teaches honest use of tools.',
   'All of band 3, plus uses in-class work and conversation to confirm understanding, follows exam board rules, and teaches when AI can help learning.',
   130),
  ('secondary_teaching', 'sec_pool_careers', 'pool', 'communication',
   'How would you help a Grade 11 learner choose subjects and plan for a career?',
   null, 200,
   'Tells the learner what to do.',
   'General advice only.',
   'Listens to the learner''s interests, gives accurate information about requirements, and involves the family.',
   'All of band 3, plus connects the learner with people and resources, and helps them make a realistic plan with a back-up.',
   140),
  ('secondary_teaching', 'sec_pool_department', 'pool', 'teamwork',
   'How have you worked with colleagues in a department to improve teaching?',
   null, 200,
   'Works alone.',
   'Shares resources sometimes.',
   'Plans together, shares assessment, and observes or is observed.',
   'Leads or contributes to a shared improvement with evidence of impact, and supports newer colleagues.',
   150)
)
insert into public.hr_bank_questions (bank_id, code, kind, competency, prompt, guidance, word_limit, rubric, sort_order)
select
  b.id, q.code, q.kind, q.competency, q.prompt, q.guidance, q.word_limit,
  jsonb_build_object('bands', jsonb_build_array(
    jsonb_build_object('band', 0, 'descriptor', 'No answer, or an answer that does not address the question.'),
    jsonb_build_object('band', 1, 'descriptor', q.b1),
    jsonb_build_object('band', 2, 'descriptor', q.b2),
    jsonb_build_object('band', 3, 'descriptor', q.b3),
    jsonb_build_object('band', 4, 'descriptor', q.b4)
  )),
  q.sort_order
from q
join public.hr_question_banks b on b.code = q.bank
on conflict (code) do update set
  prompt = excluded.prompt,
  guidance = excluded.guidance,
  word_limit = excluded.word_limit,
  rubric = excluded.rubric,
  competency = excluded.competency,
  kind = excluded.kind,
  sort_order = excluded.sort_order;
